#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi
python -m py_compile "$PYFILE"
compiled_file="${PYFILE}c"
mv "${PYFILE}c" "$compiled_file"
echo "Compiled file: $compiled_file"
